I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 161, in script
    show bash left
Exception: Image 'bash' does not accept attributes 'left'.

-- Full Traceback ------------------------------------------------------------

Traceback (most recent call last):
  File "game/script.rpy", line 161, in script
    show bash left
  File "renpy/ast.py", line 1357, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/ast.py", line 730, in show_imspec
    renpy.config.show(
    ~~~~~~~~~~~~~~~~~^
        name, at_list=at_list, layer=layer, what=expression, zorder=zorder, tag=tag, behind=behind, atl=atl
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "renpy/exports/displayexports.py", line 486, in show
    if not base.find_target() and renpy.config.missing_show:
           ~~~~~~~~~~~~~~~~^^                               
  File "renpy/display/image.py", line 444, in find_target
    self.target = target._duplicate(a)
                  ~~~~~~~~~~~~~~~~~^^^
  File "renpy/display/displayable.py", line 253, in _duplicate
    args.extraneous()
    ~~~~~~~~~~~~~~~^^
  File "renpy/display/displayable.py", line 110, in extraneous
    raise Exception(
    ...<4 lines>...
    )
Exception: Image 'bash' does not accept attributes 'left'.

Linux-6.8.0-79-generic-x86_64-with-glibc2.39 x86_64
Ren'Py 8.4.1.25072401
SFGameJamFall25 1.0
Wed Sep 24 15:29:20 2025
